modLoader="javafml"
loaderVersion="[35,)"
license="Academic Free License v3.0"

[[mods]]
modId="arandommod"
version="1.0.0"
displayName="arandommod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="joshu, MCreator"

[[dependencies.arandommod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




